server:
  enable-self-preservation: false
  port: 8761

eureka:
  instance:
    #prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: localhost
  client:
    #声明自己是个服务端
    registerWithEureka: false
    fetch-registry: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
